package net.kiranatos.snakemy;

public enum Signs {
    //https://unicode-table.com/ru/blocks/enclosed-alphanumeric-supplement/
    CIRCLE_A("A", "\uD83C\uDD50"),
    CIRCLE_B("B", "\uD83C\uDD51"),
    CIRCLE_C("C", "\uD83C\uDD52"),
    CIRCLE_D("D", "\uD83C\uDD53"),
    CIRCLE_E("E", "\uD83C\uDD54"),
    CIRCLE_F("F", "\uD83C\uDD55"),
    CIRCLE_G("G", "\uD83C\uDD56"),
    CIRCLE_H("H", "\uD83C\uDD57"),
    CIRCLE_I("I", "\uD83C\uDD58"),
    CIRCLE_J("G", "\uD83C\uDD59"),
    CIRCLE_K("K", "\uD83C\uDD5A"),
    CIRCLE_L("L", "\uD83C\uDD5B"),
    CIRCLE_M("M", "\uD83C\uDD5C"),
    CIRCLE_N("N", "\uD83C\uDD5D"),
    CIRCLE_O("O", "\uD83C\uDD5E"),
    CIRCLE_P("P", "\uD83C\uDD5F"),
    CIRCLE_Q("Q", "\uD83C\uDD60"),
    CIRCLE_R("R", "\uD83C\uDD61"),
    CIRCLE_S("S", "\uD83C\uDD62"),
    CIRCLE_T("T", "\uD83C\uDD63"),
    CIRCLE_U("U", "\uD83C\uDD64"),
    CIRCLE_V("V", "\uD83C\uDD65"),
    CIRCLE_W("W", "\uD83C\uDD66"),
    CIRCLE_X("X", "\uD83C\uDD67"),
    CIRCLE_Y("Y", "\uD83C\uDD68"),
    CIRCLE_Z("Z", "\uD83C\uDD69"),
        
    SQUARE_A("A", "\uD83C\uDD70"),
    SQUARE_B("B", "\uD83C\uDD71"),
    SQUARE_C("C", "\uD83C\uDD72"),
    SQUARE_D("D", "\uD83C\uDD73"),
    SQUARE_E("E", "\uD83C\uDD74"),
    SQUARE_F("F", "\uD83C\uDD75"),
    SQUARE_G("G", "\uD83C\uDD76"),
    SQUARE_H("H", "\uD83C\uDD77"),
    SQUARE_I("I", "\uD83C\uDD78"),
    SQUARE_J("J", "\uD83C\uDD79"),
    SQUARE_K("K", "\uD83C\uDD7A"),
    SQUARE_L("L", "\uD83C\uDD7B"),
    SQUARE_M("M", "\uD83C\uDD7C"),
    SQUARE_N("N", "\uD83C\uDD7D"),
    SQUARE_O("O", "\uD83C\uDD7E"),
    SQUARE_P("P", "\uD83C\uDD7F"),
    SQUARE_Q("Q", "\uD83C\uDD80"),
    SQUARE_R("R", "\uD83C\uDD81"),
    SQUARE_S("S", "\uD83C\uDD82"),
    SQUARE_T("T", "\uD83C\uDD83"),
    SQUARE_U("U", "\uD83C\uDD84"),
    SQUARE_V("V", "\uD83C\uDD85"),
    SQUARE_W("W", "\uD83C\uDD86"),
    SQUARE_X("X", "\uD83C\uDD87"),
    SQUARE_Y("Y", "\uD83C\uDD88"),
    SQUARE_Z("Z", "\uD83C\uDD89"),    
    
    // https://unicode-table.com/ru/blocks/katakana/
    
    // https://unicode-table.com/ru/blocks/hiragana/
    Hiragana_Letter_Small_A(    "a", "\u3041"),
    Hiragana_Letter_A(          "A", "\u3042"),
    Hiragana_Letter_Small_I(    "i", "\u3043"),
    Hiragana_Letter_I(          "I", "\u3044"),
    Hiragana_Letter_Small_U(    "u", "\u3045"),
    Hiragana_Letter_U(          "U", "\u3046"),
    Hiragana_Letter_Small_E(    "e", "\u3047"),
    Hiragana_Letter_E(          "E", "\u3048"),
    Hiragana_Letter_Small_O(    "o", "\u3049"),
    Hiragana_Letter_O(          "O", "\u304A"),
    
    Hiragana_Letter_Ka(         "ka", "\u304B"),
    Hiragana_Letter_Ga(         "ga", "\u304C"),    
    Hiragana_Letter_Ki(         "ki", "\u304D"),
    Hiragana_Letter_Gi(         "gi", "\u304E"),
    Hiragana_Letter_Ku(         "ku", "\u304F"),
    Hiragana_Letter_Gu(         "gu", "\u3050"),
    Hiragana_Letter_Ke(         "ke", "\u3051"),
    Hiragana_Letter_Ge(         "ge", "\u3052"),
    Hiragana_Letter_Ko(         "ko", "\u3053"),
    Hiragana_Letter_Go(         "go", "\u3054"),
    
    Hiragana_Letter_Sa(         "sa", "\u3055"),
    Hiragana_Letter_Za(         "za", "\u3056"),
    Hiragana_Letter_Si(         "si", "\u3057"),
    Hiragana_Letter_Zi(         "zi", "\u3058"),
    Hiragana_Letter_Su(         "su", "\u3059"),
    Hiragana_Letter_Zu(         "zu", "\u305A"),
    Hiragana_Letter_Se(         "se", "\u305B"),
    Hiragana_Letter_Ze(         "ze", "\u305C"),
    Hiragana_Letter_So(         "so", "\u305D"),
    Hiragana_Letter_Zo(         "zo", "\u305E"),
    
    Hiragana_Letter_Ta(         "ta", "\u305F"),
    Hiragana_Letter_Da(         "da", "\u3060"),    
    Hiragana_Letter_Ti(         "ti", "\u3061"),
    Hiragana_Letter_Di(         "di", "\u3062"),
    Hiragana_Letter_Small_Tu(   "tu", "\u3063"),
    Hiragana_Letter_Tu(         "tu", "\u3064"),
    Hiragana_Letter_Du(         "du", "\u3065"),
    Hiragana_Letter_Te(         "te", "\u3066"),
    Hiragana_Letter_De(         "de", "\u3067"),
    Hiragana_Letter_To(         "to", "\u3068"),
    Hiragana_Letter_Do(         "do", "\u3069"),
    
    Hiragana_Letter_Na(         "na", "\u306A"),    
    Hiragana_Letter_Ni(         "ni", "\u306B"),    
    Hiragana_Letter_Nu(         "nu", "\u306C"),    
    Hiragana_Letter_Ne(         "ne", "\u306D"),    
    Hiragana_Letter_No(         "no", "\u306E"),
    
    Hiragana_Letter_Ha(         "ha", "\u306F"),
    Hiragana_Letter_Ba(         "ba", "\u3070"),
    Hiragana_Letter_Pa(         "pa", "\u3071"),
    Hiragana_Letter_Hi(         "hi", "\u3072"),
    Hiragana_Letter_Bi(         "bi", "\u3073"),
    Hiragana_Letter_Pi(         "pi", "\u3074"),
    Hiragana_Letter_Hu(         "hu", "\u3075"),
    Hiragana_Letter_Bu(         "bu", "\u3076"),
    Hiragana_Letter_Pu(         "pu", "\u3077"),
    Hiragana_Letter_He(         "he", "\u3078"),
    Hiragana_Letter_Be(         "be", "\u3079"),
    Hiragana_Letter_Pe(         "pe", "\u307A"),
    Hiragana_Letter_Ho(         "ho", "\u307B"),
    Hiragana_Letter_Bo(         "bo", "\u307C"),
    Hiragana_Letter_Po(         "po", "\u307D"),
    
    Hiragana_Letter_Ma(         "ma", "\u307E"),    
    Hiragana_Letter_Mi(         "mi", "\u307F"),    
    Hiragana_Letter_Mu(         "mu", "\u3080"),    
    Hiragana_Letter_Me(         "me", "\u3081"),    
    Hiragana_Letter_Mo(         "mo", "\u3082"),
    
    Hiragana_Letter_Small_Ya(   "ya", "\u3083"),
    Hiragana_Letter_Ya(         "ya", "\u3084"),
    Hiragana_Letter_Small_Yu(   "yu", "\u3085"),
    Hiragana_Letter_Yu(         "yu", "\u3086"),
    Hiragana_Letter_Small_Yo(   "yo", "\u3087"),
    Hiragana_Letter_Yo(         "yo", "\u3088"),
    
    Hiragana_Letter_Ra(         "ra", "\u3089"),    
    Hiragana_Letter_Ri(         "ri", "\u308A"),    
    Hiragana_Letter_Ru(         "ru", "\u308B"),    
    Hiragana_Letter_Re(         "re", "\u308C"),    
    Hiragana_Letter_Ro(         "ro", "\u308D"),
    
    Hiragana_Letter_Small_Wa(   "wa", "\u308E"),
    Hiragana_Letter_Wa(         "wa", "\u308F"),
    Hiragana_Letter_Wi(         "wi", "\u3090"),
    Hiragana_Letter_We(         "we", "\u3091"),
    Hiragana_Letter_Wo(         "wo", "\u3092"),
    Hiragana_Letter_N(          "n", "\u3093"),
    Hiragana_Letter_Vu(         "vu", "\u3094"),
    Hiragana_Letter_Small_Ka(   "ka", "\u3095"),
    Hiragana_Letter_Small_Ke(   "ke", "\u3096"),
    
    //https://unicode-table.com/ru/blocks/miscellaneous-symbols-and-pictographs/
    AMANITA(                "AMANITA",              "\uD83C\uDF44"),
    APPLE(                  "APPLE",                "\uD83C\uDF4E"),
    CROSSED_FLAGS(          "CROSSED_FLAGS",        "\uD83C\uDF8C"),
    ALIEN_MONSTER(          "ALIEN_MONSTER",        "\uD83D\uDC7E"),
    MEDIUM_BLACK_CIRCLE(    "MEDIUM_BLACK_CIRCLE",  "\u26AB"),
    DRAGON_FACE(            "DRAGON_FACE",          "\uD83D\uDC32"),
    SPACE(                  "SPACE",                "\u0020"),
    GRAPES(                 "GRAPES",               "\uD83C\uDF47"), 
    RICE_BALL(              "GRAPES",               "\uD83C\uDF47") // real RICE_BALL - \uD83C\uDF59
                ;
    
    private String name, hexCodeUTF16BE;    
    private Signs (String name, String hexCodeUTF16BE){ 
        this.name = name;
        this.hexCodeUTF16BE = hexCodeUTF16BE;
    }
    public String getHexCodeUTF16BE() { return hexCodeUTF16BE; }    
}
